# Generated by Django 6.1.1 on 2026-09-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Instrumento/Equipo')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Físico Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=3, verbose_name='Stock Mínimo de Seguridad')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicación en Bodega')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='Precio Unitario (CLP)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='bodega.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Recepción de Proveedor / Ingreso'), ('SALIDA', 'Despacho hacia Sucursal / Franquicia')], max_length=10, verbose_name='Tipo de Operación')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de Unidades')),
                ('destino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sucursal de Destino')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Operación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bodega.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
