# Generated by Django 6.1.1 on 2026-09-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_zonabodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(max_length=10, verbose_name='Pasillo')),
                ('estante', models.CharField(max_length=10, verbose_name='Estante')),
                ('nivel', models.CharField(max_length=10, verbose_name='Nivel')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='bodega.zonabodega')),
            ],
            options={
                'verbose_name': 'Ubicación Física',
                'verbose_name_plural': 'Ubicaciones Físicas',
                'unique_together': {('zona', 'pasillo', 'estante', 'nivel')},
            },
        ),
    ]
