# Generated by Django 6.1.1 on 2026-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sucursal', models.CharField(max_length=20, unique=True, verbose_name='Código Sucursal')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Sucursal')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Santiago', max_length=80, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Sucursal de Destino',
                'verbose_name_plural': 'Sucursales de Destino',
            },
        ),
    ]
