# Generated by Django 6.1.1 on 2026-09-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_sucursaldestino'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=30, unique=True, verbose_name='Número de Guía')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'En Preparación'), ('DESPACHADO', 'En Tránsito hacia Tienda'), ('ENTREGADO', 'Recibido en Destino'), ('CANCELADO', 'Anulado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='bodega.sucursaldestino')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
            },
        ),
    ]
