# Generated by Django 6.1.1 on 2026-09-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_ordendespacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Despachada')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.ordendespacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_lineas', to='bodega.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
            },
        ),
    ]
