# Generated by Django 6.1.1 on 2026-09-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_detalledespacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('INVENTARIO_FISICO', 'Ajuste por Recuento Manual'), ('MERMA', 'Pérdida o Daño de Instrumento'), ('DEVOLUCION', 'Devolución de Garantía')], max_length=20, verbose_name='Tipo Ajuste')),
                ('cantidad_afectada', models.IntegerField(verbose_name='Diferencia (+/-)')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Auditoría')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='bodega.producto')),
            ],
            options={
                'verbose_name': 'Auditoría de Stock',
                'verbose_name_plural': 'Auditorías de Stock',
            },
        ),
    ]
